<?php
/**
 * Copyright (c) 2014 Eltrino LLC (http://eltrino.com)
 *
 * Licensed under the Open Software License (OSL 3.0).
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://opensource.org/licenses/osl-3.0.php
 *
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@eltrino.com so we can send you a copy immediately.
 */
?>
<?php /* @var $this Eltrino_DiamanteDesk_Block_Adminhtml_Sales_Order_View_Info */ ?>
<div id="diamantedesk_ticket_form">
    <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Create Ticket') ?></h4>
            </div>

            <fieldset>
                <?php echo $this->getLayout()->createBlock('eltrino_diamantedesk/adminhtml_sales_order_view_form', 'diamantedesk_ticket_form')->toHtml(); ?>
            </fieldset>

        </div>
    </div>
    <div class="clear"></div>
</div>